<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Interop\Windows\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lyt.MediaFoundation.Interop\Lyt.MediaFoundation.Interop.csproj" />
  </ItemGroup>

</Project>
