
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationIcon>qrcode.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lyt.QrCode.Creator\Lyt.QrCode.Creator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.0" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.0" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="start /WAIT ..\Tools\prebuild.bat&#xD;&#xA;" />
  </Target>

  <ItemGroup>
    <AvaloniaResource Remove="puzzle.ico" />
  </ItemGroup>
</Project>
