<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>IDE0079</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>IDE0079</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="Avalonia">
    <AvaloniaXamlVerboseExceptions>True</AvaloniaXamlVerboseExceptions>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.0" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.0" />
    <PackageReference Include="Lyt.QrCode" Version="1.0.3" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.92.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="Assets\Images\**" />
    <AvaloniaResource Include="Assets\Languages\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Controls\Lyt.Avalonia.Controls.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Interfaces\Lyt.Avalonia.Interfaces.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Localizer\Lyt.Avalonia.Localizer.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Mvvm\Lyt.Avalonia.Mvvm.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.FileSystem\Lyt.FileSystem.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Framework.Interfaces\Lyt.Framework.Interfaces.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Model\Lyt.Model.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Mvvm\Lyt.Mvvm.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Persistence\Lyt.Persistence.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Utilities\Lyt.Utilities.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Validation\Lyt.Validation.csproj" />
    <ProjectReference Include="..\Lyt.QrCode.Creator.Model\Lyt.QrCode.Creator.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Workflow\Encoding\DesignForms\SizeFormatView.axaml.cs">
      <DependentUpon>SizeFormatView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\DesignForms\ImageView.axaml.cs">
      <DependentUpon>ImageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\DesignForms\ShapesView.axaml.cs">
      <DependentUpon>ShapesView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\DesignForms\ColorsView.axaml.cs">
      <DependentUpon>ColorsView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\DesignForms\LogoView.axaml.cs">
      <DependentUpon>LogoView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\DesignForms\FrameView.axaml.cs">
      <DependentUpon>FrameView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\ContentView.axaml.cs">
      <DependentUpon>ContentView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\TestImageView.axaml.cs">
      <DependentUpon>TestImageView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
