<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>IDE0079</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>IDE0079</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="Avalonia">
    <AvaloniaXamlVerboseExceptions>True</AvaloniaXamlVerboseExceptions>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.0" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.1.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="Assets\Images\**" />
    <AvaloniaResource Include="Assets\Languages\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Controls\Lyt.Avalonia.Controls.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Interfaces\Lyt.Avalonia.Interfaces.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Localizer\Lyt.Avalonia.Localizer.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Mvvm\Lyt.Avalonia.Mvvm.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.FileSystem\Lyt.FileSystem.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Framework.Interfaces\Lyt.Framework.Interfaces.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Model\Lyt.Model.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Mvvm\Lyt.Mvvm.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Persistence\Lyt.Persistence.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Utilities\Lyt.Utilities.csproj" />
    <ProjectReference Include="..\Lyt.QrCode.Creator.Model\Lyt.QrCode.Creator.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Workflow\Encoding\ContentForms\WifiView.axaml.cs">
      <DependentUpon>WifiView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\ContentForms\VCardView.axaml.cs">
      <DependentUpon>VCardView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\ContentForms\UrlView.axaml.cs">
      <DependentUpon>UrlView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\ContentForms\TextMessageView.axaml.cs">
      <DependentUpon>TextMessageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\ContentForms\PhoneNumberView.axaml.cs">
      <DependentUpon>PhoneNumberView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\ContentForms\MeCardView.axaml.cs">
      <DependentUpon>MeCardView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\ContentForms\MailView.axaml.cs">
      <DependentUpon>MailView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\ContentForms\GeoLocationView.axaml.cs">
      <DependentUpon>GeoLocationView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\ContentForms\CalendarEventView.axaml.cs">
      <DependentUpon>CalendarEventView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Encoding\EncodingView.axaml.cs">
      <DependentUpon>EncodingView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
